### ISSUE TITLE
Crash on startup - Fabric 1.19.2

### ISSUE THREAD

**Issue by spunchbop121** [KrLite/Tap-Tab#3]
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'taptab'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_3414 net.minecraft.class_3414.method_47908(net.minecraft.class_2960)'
	at net.krlite.taptab.TapTabClient$Sounds.<clinit>(TapTabClient.java:47)
	at net.krlite.taptab.TapTabClient.onInitializeClient(TapTabClient.java:59)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more

**Comment by KrLite** [comment]
Thank you for reporting, it will be fixed soon.

**What caused this:** Mojang has changed a lot between 1.19.2 and 1.19.3, and that is really annoying sometime. Mods made for 1.19.3 can just incompatible with 1.19.2.

**Comment by KrLite** [comment]
Now the version is separated.

<img width="137" alt="image" src="https://user-images.githubusercontent.com/68179735/215240948-bdd9230e-c3f1-49da-ba15-54d38898343d.png">
